<template>
  <div>
    <Scroll class="content">
      <ul>
          <li>asdasdasd1</li>
          <li>asdasdasd2</li>
          <li>asdasdasd3</li>
          <li>asdasdasd4</li>
          <li>asdasdasd5</li>
          <li>asdasdasd6</li>
          <li>asdasdasd7</li>
          <li>asdasdasd8</li>
          <li>asdasdasd9</li>
          <li>asdasdasd10</li>
          <li>asdasdasd11</li>
          <li>asdasdasd12</li>
          <li>asdasdasd13</li>
          <li>asdasdasd14</li>
          <li>asdasdasd15</li>
          <li>asdasdasd16</li>
          <li>asdasdasd17</li>
          <li>asdasdasd18</li>
          <li>asdasdasd19</li>
          <li>asdasdasd20</li>
          <li>asdasdasd21</li>
          <li>asdasdasd22</li>
          <li>asdasdasd23</li>
          <li>asdasdasd24</li>
          <li>asdasdasd25</li>
          <li>asdasdasd26</li>
          <li>asdasdasd27</li>
          <li>asdasdasd28</li>
          <li>asdasdasd29</li>
          <li>asdasdasd30</li>
          <li>asdasdasd31</li>
          <li>asdasdasd32</li>
          <li>asdasdasd33</li>
          <li>asdasdasd34</li>
          <li>asdasdasd35</li>
          <li>asdasdasd36</li>
          <li>asdasdasd37</li>
          <li>asdasdasd38</li>
          <li>asdasdasd39</li>
          <li>asdasdasd40</li>
          <li>asdasdasd41</li>
          <li>asdasdasd42</li>
          <li>asdasdasd43</li>
          <li>asdasdasd44</li>
          <li>asdasdasd45</li>
          <li>asdasdasd46</li>
          <li>asdasdasd47</li>
          <li>asdasdasd48</li>
          <li>asdasdasd49</li>
          <li>asdasdasd50</li>
          <li>asdasdasd51</li>
          <li>asdasdasd52</li>
          <li>asdasdasd53</li>
          <li>asdasdasd54</li>
          <li>asdasdasd55</li>
          <li>asdasdasd56</li>
          <li>asdasdasd57</li>
          <li>asdasdasd58</li>
          <li>asdasdasd59</li>
          <li>asdasdasd60</li>
          <li>asdasdasd61</li>
          <li>asdasdasd62</li>
          <li>asdasdasd63</li>
          <li>asdasdasd64</li>
          <li>asdasdasd65</li>
          <li>asdasdasd66</li>
          <li>asdasdasd67</li>
          <li>asdasdasd68</li>
          <li>asdasdasd69</li>
          <li>asdasdasd70</li>
          <li>asdasdasd71</li>
          <li>asdasdasd72</li>
          <li>asdasdasd73</li>
          <li>asdasdasd74</li>
          <li>asdasdasd75</li>
          <li>asdasdasd76</li>
          <li>asdasdasd77</li>
          <li>asdasdasd78</li>
          <li>asdasdasd79</li>
          <li>asdasdasd80</li>
          <li>asdasdasd81</li>
          <li>asdasdasd82</li>
          <li>asdasdasd83</li>
          <li>asdasdasd84</li>
          <li>asdasdasd85</li>
          <li>asdasdasd86</li>
          <li>asdasdasd87</li>
          <li>asdasdasd88</li>
          <li>asdasdasd89</li>
          <li>asdasdasd90</li>
          <li>asdasdasd91</li>
          <li>asdasdasd92</li>
          <li>asdasdasd93</li>
          <li>asdasdasd94</li>
          <li>asdasdasd95</li>
          <li>asdasdasd96</li>
          <li>asdasdasd97</li>
          <li>asdasdasd98</li>
          <li>asdasdasd99</li>
          <li>asdasdasd100</li>
        </ul>
    </Scroll>
  </div>
</template>

<script>
import Scroll from "components/common/scroll/Scroll";
export default {
    name:"Profile",
    components:{
      Scroll
    }
}
</script>

<style scoped>
.content{
  height: 300px;
  background-color: red;
  overflow: hidden;
}
</style>